class LevelManager {
  constructor() {
    this.enemyConfigs = this.generateEnemyConfigs();
    this.levels = this.generateLevels();

    this.currentLevel = 0;
    this.maxLevel = Object.keys(this.levels).length;
    this.currentWave = 0;
  }

  startNextLevel() {
    this.currentLevel++;
    this.currentWave = 0;

    return this.currentLevel;
  }

  getNextWave() {
    this.currentWave++;
    const nextWave = this.levels[this.currentLevel - 1].enemyWaves[this.currentWave - 1];
    return nextWave;
  }

  isLastWave() {
    return this.currentWave === this.levels[this.currentLevel - 1].enemyWaves.length;
  }

  isLastLevel() {
    return this.currentLevel === this.maxLevel;
  }

  generateEnemyConfigs() {
    return {
      "exploder1": new EnemyConfig("exploder1", 54, 64, ["./assets/images/enemies/exploder1_1.png", "./assets/images/enemies/exploder1_2.png"], "./assets/images/enemies/green_splatter.png", null, 128, 25, 50, "exploding", 0, 0, 0, 0, 0, true),

      "exploderBoss": new EnemyConfig("exploderBoss", 108, 128, ["./assets/images/enemies/exploder1_1.png", "./assets/images/enemies/exploder1_2.png"], "./assets/images/enemies/green_splatter.png", null, 128, 400, 50, "exploding", 0, 0, 0, 0, 0, true),

      "venomShooter": new EnemyConfig("venomShooter", 52, 64, ["./assets/images/enemies/venom_shooter_1.png", "./assets/images/enemies/venom_shooter_2.png"], "./assets/images/enemies/green_splatter.png", "./assets/images/enemies/venom_ball.png", 128, 50, 25, "shooting", 0.33, 100, 16, 48, 10, true),

      "venomShooterBoss": new EnemyConfig("venomShooterBoss", 104, 128, ["./assets/images/enemies/venom_shooter_1.png", "./assets/images/enemies/venom_shooter_2.png"], "./assets/images/enemies/green_splatter.png", "./assets/images/enemies/venom_ball.png", 128, 600, 25, "shooting", 0.33, 100, 32, 96, 25, true),

      "exploder2": new EnemyConfig("exploder2", 54, 64, ["./assets/images/enemies/exploder2_1.png"], "./assets/images/enemies/blue_splatter.png", null, 128, 20, 125, "exploding", 0, 0, 0, 0, 0, true),

      "exploder2Boss": new EnemyConfig("exploder2", 108, 128, ["./assets/images/enemies/exploder2_1.png"], "./assets/images/enemies/blue_splatter.png", null, 128, 700, 75, "exploding", 0, 0, 0, 0, 0, true),

      "robotSoldier": new EnemyConfig("robotSoldier", 36, 48, ["./assets/images/enemies/robot_soldier_1.png", "./assets/images/enemies/robot_soldier_2.png"], "./assets/images/enemies/blue_splatter.png", "./assets/images/enemies/energy_ball.png", 128, 75, 30, "shooting", 0.5, 100, 16, 16, 15, true),

      "robotSoldierBoss": new EnemyConfig("robotSoldierBoss", 72, 96, ["./assets/images/enemies/robot_soldier_1.png", "./assets/images/enemies/robot_soldier_2.png"], "./assets/images/enemies/blue_splatter.png", "./assets/images/enemies/energy_ball.png", 128, 1000, 30, "shooting", 0.5, 100, 24, 24, 30, true),

      "energyShooter": new EnemyConfig("energyShooter", 64, 64, ["./assets/images/enemies/energy_shooter_1.png", "./assets/images/enemies/energy_shooter_2.png"], "./assets/images/enemies/blue_splatter.png", "./assets/images/enemies/energy_ball.png", 128, 100, 20, "shooting", 0.33, 100, 24, 24, 20, false),

      "energyShooterBoss": new EnemyConfig("energyShooterBoss", 128, 128, ["./assets/images/enemies/energy_shooter_1.png", "./assets/images/enemies/energy_shooter_2.png"], "./assets/images/enemies/blue_splatter.png", "./assets/images/enemies/energy_ball.png", 128, 1500, 20, "shooting", 0.4, 100, 48, 48, 35, false),
    };
  }

  generateLevels() {
    return {
        0: new Level([
        [
          this.enemyConfigs["exploder1"],
        ],
        [
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
        ],
        [
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
        ],
        [
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
        ],
        [
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
        ],
      ]),
      1: new Level([
        [
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
        ],
        [
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
        ],
        [
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
        ],
        [
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
        ],
        [
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
        ],
      ]),
      2: new Level([
        [
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["venomShooter"],
        ],
        [
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
        ],
        [
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["venomShooter"],
        ],
        [
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
        ],
        [
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["venomShooter"],
        ],
      ]),
      3: new Level([
        [
          this.enemyConfigs["venomShooter"],
          this.enemyConfigs["venomShooter"],
        ],
        [
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["venomShooter"],
        ],
        [
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["venomShooter"],
        ],
        [
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
        ],
        [
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["venomShooter"],
        ],
      ]),
      4: new Level([
        [
          this.enemyConfigs["exploderBoss"],
        ]
      ]),
      5: new Level([
        [
          this.enemyConfigs["venomShooter"],
          this.enemyConfigs["venomShooter"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
        ],
        [
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["venomShooter"],
        ],
        [
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["venomShooter"],
          this.enemyConfigs["venomShooter"],
        ],
        [
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
        ],
        [
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["venomShooter"],
          this.enemyConfigs["venomShooter"],
        ],
      ]),
      6: new Level([
        [
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
        ],
        [
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["venomShooter"],
        ],
        [
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["venomShooter"],
          this.enemyConfigs["venomShooter"],
        ],
        [
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
        ],
        [
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["venomShooter"],
          this.enemyConfigs["venomShooter"],
        ],
      ]),
      7: new Level([
        [
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
        ],
        [
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
        ],
        [
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
        ],
        [
          this.enemyConfigs["venomShooter"],
          this.enemyConfigs["venomShooter"],
          this.enemyConfigs["venomShooter"],
        ],
        [
          this.enemyConfigs["venomShooter"],
          this.enemyConfigs["venomShooter"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
        ],
      ]),
      8: new Level([
        [
          this.enemyConfigs["venomShooter"],
          this.enemyConfigs["venomShooter"],
          this.enemyConfigs["venomShooter"],
          this.enemyConfigs["venomShooter"],
        ],
        [
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
        ],
        [
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
        ],
        [
          this.enemyConfigs["venomShooter"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
        ],
        [
          this.enemyConfigs["venomShooter"],
          this.enemyConfigs["venomShooter"],
          this.enemyConfigs["venomShooter"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
        ],
      ]),
      9: new Level([
        [
          this.enemyConfigs["venomShooterBoss"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
        ]
      ]),
      10: new Level([
        [
          this.enemyConfigs["exploder2"],
        ],
        [
          this.enemyConfigs["exploder2"],
          this.enemyConfigs["exploder2"],
        ],
        [
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder2"],
          this.enemyConfigs["exploder2"],
        ],
        [
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder2"],
        ],
        [
          this.enemyConfigs["exploder2"],
          this.enemyConfigs["exploder2"],
          this.enemyConfigs["exploder2"],
          this.enemyConfigs["exploder2"],
        ],
      ]),
      11: new Level([
        [
          this.enemyConfigs["exploder2"],
          this.enemyConfigs["exploder2"],
          this.enemyConfigs["exploder2"],
        ],
        [
          this.enemyConfigs["exploder2"],
          this.enemyConfigs["exploder2"],
          this.enemyConfigs["exploder2"],
          this.enemyConfigs["exploder2"],
        ],
        [
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["venomShooter"],
          this.enemyConfigs["exploder2"],
          this.enemyConfigs["exploder2"],
        ],
        [
          this.enemyConfigs["venomShooter"],
          this.enemyConfigs["venomShooter"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder2"],
        ],
        [
          this.enemyConfigs["venomShooter"],
          this.enemyConfigs["venomShooter"],
          this.enemyConfigs["exploder2"],
          this.enemyConfigs["exploder2"],
        ],
      ]),
      12: new Level([
        [
          this.enemyConfigs["exploder2"],
          this.enemyConfigs["exploder2"],
          this.enemyConfigs["robotSoldier"],
        ],
        [
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["robotSoldier"],
          this.enemyConfigs["robotSoldier"],
        ],
        [
          this.enemyConfigs["robotSoldier"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["venomShooter"],
          this.enemyConfigs["exploder2"],
          this.enemyConfigs["exploder2"],
        ],
        [
          this.enemyConfigs["robotSoldier"],
          this.enemyConfigs["venomShooter"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder2"],
        ],
        [
          this.enemyConfigs["robotSoldier"],
          this.enemyConfigs["robotSoldier"],
          this.enemyConfigs["exploder2"],
          this.enemyConfigs["exploder2"],
          this.enemyConfigs["exploder2"],
        ],
      ]),
      13: new Level([
        [
          this.enemyConfigs["exploder2"],
          this.enemyConfigs["robotSoldier"],
          this.enemyConfigs["robotSoldier"],
          this.enemyConfigs["robotSoldier"],
        ],
        [
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder2"],
          this.enemyConfigs["exploder2"],
          this.enemyConfigs["robotSoldier"],
          this.enemyConfigs["robotSoldier"],
        ],
        [
          this.enemyConfigs["robotSoldier"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["venomShooter"],
          this.enemyConfigs["exploder2"],
          this.enemyConfigs["exploder2"],
        ],
        [
          this.enemyConfigs["robotSoldier"],
          this.enemyConfigs["venomShooter"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder2"],
          this.enemyConfigs["exploder2"],
        ],
        [
          this.enemyConfigs["robotSoldier"],
          this.enemyConfigs["robotSoldier"],
          this.enemyConfigs["robotSoldier"],
          this.enemyConfigs["exploder2"],
          this.enemyConfigs["exploder2"],
          this.enemyConfigs["exploder2"],
        ],
      ]),
      14: new Level([
        [
          this.enemyConfigs["exploder2Boss"],
        ]
      ]),
      15: new Level([
        [
          this.enemyConfigs["exploder2"],
          this.enemyConfigs["robotSoldier"],
          this.enemyConfigs["robotSoldier"],
          this.enemyConfigs["robotSoldier"],
        ],
        [
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder2"],
          this.enemyConfigs["exploder2"],
          this.enemyConfigs["robotSoldier"],
          this.enemyConfigs["robotSoldier"],
        ],
        [
          this.enemyConfigs["robotSoldier"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["venomShooter"],
          this.enemyConfigs["exploder2"],
          this.enemyConfigs["exploder2"],
        ],
        [
          this.enemyConfigs["robotSoldier"],
          this.enemyConfigs["venomShooter"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder2"],
          this.enemyConfigs["exploder2"],
        ],
        [
          this.enemyConfigs["robotSoldier"],
          this.enemyConfigs["robotSoldier"],
          this.enemyConfigs["robotSoldier"],
          this.enemyConfigs["exploder2"],
          this.enemyConfigs["exploder2"],
          this.enemyConfigs["exploder2"],
        ],
      ]),
      16: new Level([
        [
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder2"],
          this.enemyConfigs["robotSoldier"],
          this.enemyConfigs["robotSoldier"],
          this.enemyConfigs["robotSoldier"],
        ],
        [
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder2"],
          this.enemyConfigs["exploder2"],
          this.enemyConfigs["robotSoldier"],
          this.enemyConfigs["robotSoldier"],
        ],
        [
          this.enemyConfigs["robotSoldier"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["venomShooter"],
          this.enemyConfigs["exploder2"],
          this.enemyConfigs["exploder2"],
          this.enemyConfigs["exploder2"],
        ],
        [
          this.enemyConfigs["robotSoldier"],
          this.enemyConfigs["venomShooter"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder2"],
          this.enemyConfigs["exploder2"],
          this.enemyConfigs["exploder2"],
        ],
        [
          this.enemyConfigs["exploderBoss"],
          this.enemyConfigs["exploderBoss"],
        ],
      ]),
      17: new Level([
        [
          this.enemyConfigs["exploder2"],
          this.enemyConfigs["exploder2"],
          this.enemyConfigs["exploder2"],
          this.enemyConfigs["energyShooter"],
        ],
        [
          this.enemyConfigs["exploder2"],
          this.enemyConfigs["exploder2"],
          this.enemyConfigs["exploder2"],
          this.enemyConfigs["exploder2"],
          this.enemyConfigs["energyShooter"],
          this.enemyConfigs["energyShooter"],
        ],
        [
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["energyShooter"],
          this.enemyConfigs["energyShooter"],
          this.enemyConfigs["energyShooter"],
        ],
        [
          this.enemyConfigs["robotSoldier"],
          this.enemyConfigs["robotSoldier"],
          this.enemyConfigs["energyShooter"],
          this.enemyConfigs["energyShooter"],
          this.enemyConfigs["energyShooter"],
        ],
        [
          this.enemyConfigs["exploder2"],
          this.enemyConfigs["exploder2"],
          this.enemyConfigs["robotSoldier"],
          this.enemyConfigs["robotSoldier"],
          this.enemyConfigs["energyShooter"],
          this.enemyConfigs["energyShooter"],
        ],
      ]),
      18: new Level([
        [
          this.enemyConfigs["exploder2"],
          this.enemyConfigs["exploder2"],
          this.enemyConfigs["exploder2"],
          this.enemyConfigs["energyShooter"],
          this.enemyConfigs["energyShooter"],
          this.enemyConfigs["energyShooter"],
        ],
        [
          this.enemyConfigs["energyShooter"],
          this.enemyConfigs["energyShooter"],
          this.enemyConfigs["energyShooter"],
          this.enemyConfigs["energyShooter"],
        ],
        [
          this.enemyConfigs["robotSoldier"],
          this.enemyConfigs["robotSoldier"],
          this.enemyConfigs["energyShooter"],
          this.enemyConfigs["energyShooter"],
          this.enemyConfigs["energyShooter"],
        ],
        [
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["robotSoldier"],
          this.enemyConfigs["robotSoldier"],
          this.enemyConfigs["energyShooter"],
          this.enemyConfigs["energyShooter"],
          this.enemyConfigs["energyShooter"],
        ],
        [
          this.enemyConfigs["exploder2"],
          this.enemyConfigs["exploder2"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["exploder1"],
          this.enemyConfigs["robotSoldier"],
          this.enemyConfigs["robotSoldier"],
          this.enemyConfigs["robotSoldier"],
          this.enemyConfigs["energyShooter"],
          this.enemyConfigs["energyShooter"],
          this.enemyConfigs["energyShooter"],
        ],
      ]),
      19: new Level([
        [
          this.enemyConfigs["exploderBoss"],
        ],
        [
          this.enemyConfigs["exploderBoss"],
          this.enemyConfigs["exploderBoss"],
        ],
        [
          this.enemyConfigs["exploder2Boss"],
        ],
        [
          this.enemyConfigs["robotSoldierBoss"],
        ],
        [
          this.enemyConfigs["energyShooterBoss"],
        ],
      ]),
    };
  }
}
